[2024-09-09T13:53:00.449+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-09T13:53:00.460+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-09T13:46:56.669632+00:00 [queued]>
[2024-09-09T13:53:00.465+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-09T13:46:56.669632+00:00 [queued]>
[2024-09-09T13:53:00.466+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-09-09T13:53:00.475+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-09-09 13:46:56.669632+00:00
[2024-09-09T13:53:00.480+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_python_operator_hook', 'call_api_task', 'manual__2024-09-09T13:46:56.669632+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/example_python_operator_hook.py', '--cfg-path', '/tmp/tmpp013y6v_']
[2024-09-09T13:53:00.482+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask call_api_task
[2024-09-09T13:53:00.483+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=537) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-09T13:53:00.483+0000] {standard_task_runner.py:63} INFO - Started process 539 to run task
[2024-09-09T13:53:00.510+0000] {task_command.py:426} INFO - Running <TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-09T13:46:56.669632+00:00 [running]> on host d3466d5464ee
[2024-09-09T13:53:00.567+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_python_operator_hook' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T13:46:56.669632+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-09T13:46:56.669632+00:00'
[2024-09-09T13:53:00.568+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-09T13:53:00.666+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-09T13:53:00.666+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: call_api() missing 1 required positional argument: 'end_date'
[2024-09-09T13:53:00.672+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=example_python_operator_hook, task_id=call_api_task, run_id=manual__2024-09-09T13:46:56.669632+00:00, execution_date=20240909T134656, start_date=20240909T135300, end_date=20240909T135300
[2024-09-09T13:53:00.680+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task call_api_task (call_api() missing 1 required positional argument: 'end_date'; 539)
[2024-09-09T13:53:00.697+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-09T13:53:00.707+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-09T13:53:00.709+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
