[2024-09-12T22:45:58.740+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-12T22:45:58.750+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-12T22:45:57.772737+00:00 [queued]>
[2024-09-12T22:45:58.756+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-12T22:45:57.772737+00:00 [queued]>
[2024-09-12T22:45:58.757+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-12T22:45:58.766+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-09-12 22:45:57.772737+00:00
[2024-09-12T22:45:58.773+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2502) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-12T22:45:58.772+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_python_operator_hook', 'call_api_task', 'manual__2024-09-12T22:45:57.772737+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/example_python_operator_hook.py', '--cfg-path', '/tmp/tmpryz3sd63']
[2024-09-12T22:45:58.773+0000] {standard_task_runner.py:63} INFO - Started process 2504 to run task
[2024-09-12T22:45:58.773+0000] {standard_task_runner.py:91} INFO - Job 118: Subtask call_api_task
[2024-09-12T22:45:58.801+0000] {task_command.py:426} INFO - Running <TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-12T22:45:57.772737+00:00 [running]> on host 1ab47b72986b
[2024-09-12T22:45:58.866+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_python_operator_hook' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T22:45:57.772737+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T22:45:57.772737+00:00'
[2024-09-12T22:45:58.867+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-12T22:45:58.884+0000] {base.py:84} INFO - Using connection ID 'ingestion_api' for task execution.
[2024-09-12T22:45:59.130+0000] {logging_mixin.py:188} INFO - DataFrame saved to PostgreSQL successfully.
[2024-09-12T22:45:59.135+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-12T22:45:59.138+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-09-12T22:45:59.180+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/google/cloud/bigquery/_pandas_helpers.py:537 UserWarning: Pyarrow could not determine the type of columns: snow_depth.
[2024-09-12T22:46:03.875+0000] {logging_mixin.py:188} INFO - DataFrame uploaded to BigQuery table: pacific-ethos-433305-u0.The_Weather_Data.The_Weather_Table
[2024-09-12T22:46:03.876+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-12T22:46:03.876+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-12T22:46:03.882+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=example_python_operator_hook, task_id=call_api_task, run_id=manual__2024-09-12T22:45:57.772737+00:00, execution_date=20240912T224557, start_date=20240912T224558, end_date=20240912T224603
[2024-09-12T22:46:03.907+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-12T22:46:03.917+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T22:46:03.918+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
